### ISSUE TITLE
Catching unshelving (and other errors)

### ISSUE THREAD

**Issue by muratmaga** [MorphoCloud/MorphoCloudWorkflow#36] opened 2024-09-07 04:00 UTC
I have unshelved instance-32. Command successfully executed, but the instance didn't become online at JS2, it showed an "error" state (there was no more information about what the error was). Status label on the MC issue page was active. 

I am currently manually rebooting the instance from the exosphere side to see if that's going to resolve the error (in previous situations it did). 

There is really nothing user can do on their end to fix this problem. We should create an automated email to morphocloud@outlook.com (or whatever we provided as the support contact in the email text) so that one of us can take a look.

**Comment by muratmaga** [comment] 2024-09-07 04:00
FYI this is instance still erroring after the reboot. Maybe a JS2 problem?

**Comment by muratmaga** [comment] 2024-09-07 04:07
More insights: Web Desktop/Shell on exosphere side is disabled, I can't ssh into it, because passphrase is shown as Not available. However, I can use the console link to get connected to the instance. UI looks different, it is not the our xfce4 interface. Slicer is there with extension and can be run. It seems it is a mixed state of configuration. 
<img width="1031" alt="image" src="https://github.com/user-attachments/assets/17e027e0-b604-400a-bdca-786dd59ff49d">

**Comment by jcfr** [comment] 2024-09-07 10:36
Thanks for the report, this may be related to the update of exosphere. I will have a look.

**Comment by jcfr** [comment] 2024-10-01 05:16
Closing. Unable to reproduce.

**Closed by jcfr** 2024-10-01 05:16 UTC
Labels: enhancement, wontfix

**Comment by jcfr** [comment] 2024-10-01 05:17
Issue likely fixed through d4e1ccba6dcd7 (`fix(actions/control-instance): Remove hard-coded instance name for task state check`)
